//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJG.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeneyim
    {
        public int ID { get; set; }
        public string egitimBaslik { get; set; }
        public string egitimAciklama { get; set; }
        public string egitimTarih { get; set; }
        public string hizmetBaslik { get; set; }
        public string hizmetAciklama { get; set; }
        public string hizmetTarih { get; set; }
    }
}
