//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJG.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHizmetler
    {
        public int ID { get; set; }
        public string aciklama { get; set; }
        public string baslik { get; set; }
        public string ico { get; set; }
    }
}
